name: L'intégration continue
permissions: {}

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Exécute les tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Utilise la version Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Installe les dépendances
        run: npm ci

      - name: Exécute les tests
        run: npm run test
